### ISSUE TITLE
Autoren zu Buchtitel zuweisen

### ISSUE THREAD

**Issue by Unknof** [Unknof/DH1_Project#2]
Hier (https://en.wikipedia.org/wiki/List_of_Dungeons_%26_Dragons_rulebooks) bekommt man alle die Autorentitel der meisten Bücher. Evtl scrapen oder händisch machen (ist aber sehr einfach zu scrapen, weil Wikipedia)

**Comment by Unknof** [comment]
Die References sind bullshit (Ich darf nich mit # meine Zeilen anfangen)

**Comment by x-laura-x** [comment]
erledigt :)
