### ISSUE TITLE
CR in einen metrischen Wertebereich konventieren

### ISSUE THREAD

**Issue by Unknof** [Unknof/DH1_Project#8]
Wie in Whatsapp beschrieben.

**Comment by Unknof** [comment]
Ich weiß das mal Laura zu, da ich denke das wäre eine nette Aufgabe um ein bisschen SQL anzuwenden. Wenn du keine Lust/Zeit hast, sag bitte einfach bescheid dann kann ich mich auch drum kümmern.

**Comment by x-laura-x** [comment]
erledigt :)
